name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - main  # or your target branch
  pull_request:
    branches:
      - main  # or your target branch

jobs:
  trigger-ado-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Trigger Azure DevOps Pipeline
      env:
        AZDO_PAT: CWtQuKy2XaplgHdkmf8me0IJmOfN4tN9PrbHODDEcdsltuXx1XHAJQQJ99ALACAAAAADfmnNAAASAZDO7xKD  # Store your Azure DevOps PAT in GitHub secrets
        AZDO_ORG: 'https://sqsglobal.visualstudio.com/tvsmsoftwarefactory'  # Replace with your Azure DevOps organization URL
        AZDO_PROJECT: 'tvsmsoftwarefactory'  # Replace with your Azure DevOps project name
        AZDO_PIPELINE: 'azure-ado-1'  # Replace with your Azure DevOps pipeline name
      run: |
        curl -u :$AZDO_PAT \
             -X POST \
             -H "Content-Type: application/json" \
             -d '{}' \
             "$AZDO_ORG/$AZDO_PROJECT/_apis/pipelines/$AZDO_PIPELINE/runs?api-version=6.0-preview.1"
