name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - main  # or your target branch
  pull_request:
    branches:
      - main  # or your target branch

jobs:
  trigger-ado-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Trigger Azure DevOps Pipeline
      run: |
        curl -u ":CWtQuKy2XaplgHdkmf8me0IJmOfN4tN9PrbHODDEcdsltuXx1XHAJQQJ99ALACAAAAADfmnNAAASAZDO7xKD" \
             -X POST \
             -H "Content-Type: application/json" \
             -d '{}' \
             "https://sqsglobal.visualstudio.com/tvsmsoftwarefactory/_apis/pipelines/azure-ado-1/runs?api-version=6.0-preview.1"
