name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - main  # or your target branch
  pull_request:
    branches:
      - main  # or your target branch

jobs:
  trigger-ado-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Trigger Azure DevOps Pipeline
      run: |
        curl -u ":D8aMf97d9qtBuYdA19ftAWWRjSKj63sDuahr9Uqn9IpH8qYMfpZ8JQQJ99ALACAAAAADfmnNAAASAZDO5WXI" \
             -X POST \
             -H "Content-Type: application/json" \
             -d '{}' \
             "https://dev.azure.com/chetansingare/POC/_apis/pipelines/sample/runs?api-version=6.0-preview.1"
