name: Trigger Azure DevOps Pipeline
 
on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the pipeline on
 
jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
 
    steps:
    - name: Trigger Azure DevOps Pipeline
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        ORGANIZATION="chetansingare"
        PROJECT="sample"
        PIPELINE_ID="19" # Replace with the Azure DevOps pipeline ID
 
        # Trigger the pipeline using Azure DevOps REST API
        curl -u ":D8aMf97d9qtBuYdA19ftAWWRjSKj63sDuahr9Uqn9IpH8qYMfpZ8JQQJ99ALACAAAAADfmnNAAASAZDO5WXI" \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{}' \
          "https://dev.azure.com/$ORGANIZATION/$PROJECT/_apis/pipelines/$PIPELINE_ID/runs?api-version=7.1-preview.1"
